[package]
name = "wt-api"
version = "1.0.0"
authors = ["X-rays5 <thomas@scheenen.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cfg-if = "1.0.0"
worker = "0.0.9"
serde = "1.0.136"
serde_json = "1.0.79"
scraper = "0.13.0"
console_error_panic_hook = { version = "0.1.7", optional = true }
lazy_static = "1.4.0"

[profile.release]
opt-level = "s"